export const estados = [
	{
		iso_31662: 'VE-X',
		estado: 'Amazonas',
		capital: 'Puerto Ayacucho',
		id_estado: 1,
	},
	{
		iso_31662: 'VE-B',
		estado: 'Anzoátegui',
		capital: 'Barcelona',
		id_estado: 2,
	},
	{
		iso_31662: 'VE-C',
		estado: 'Apure',
		capital: 'San Fernando de Apure',
		id_estado: 3,
	},
	{
		iso_31662: 'VE-D',
		estado: 'Aragua',
		capital: 'Maracay',
		id_estado: 4,
	},
	{
		iso_31662: 'VE-E',
		estado: 'Barinas',
		capital: 'Barinas',
		id_estado: 5,
	},
	{
		iso_31662: 'VE-F',
		estado: 'Bolívar',
		capital: 'Ciudad Bolívar',
		id_estado: 6,
	},
	{
		iso_31662: 'VE-G',
		estado: 'Carabobo',
		capital: 'Valencia',
		id_estado: 7,
	},
	{
		iso_31662: 'VE-H',
		estado: 'Cojedes',
		capital: 'San Carlos',
		id_estado: 8,
	},
	{
		iso_31662: 'VE-Y',
		estado: 'Delta Amacuro',
		capital: 'Tucupita',
		id_estado: 9,
	},
	{
		iso_31662: 'VE-I',
		estado: 'Falcón',
		capital: 'Coro',
		id_estado: 10,
	},
	{
		iso_31662: 'VE-J',
		estado: 'Guárico',
		capital: 'San Juan de Los Morros',
		id_estado: 11,
	},
	{
		iso_31662: 'VE-K',
		estado: 'Lara',
		capital: 'Barquisimeto',
		id_estado: 12,
	},
	{
		iso_31662: 'VE-L',
		estado: 'Mérida',
		capital: 'Mérida',
		id_estado: 13,
	},
	{
		iso_31662: 'VE-M',
		estado: 'Miranda',
		capital: 'Los Teques',
		id_estado: 14,
	},
	{
		iso_31662: 'VE-N',
		estado: 'Monagas',
		capital: 'Maturín',
		id_estado: 15,
	},
	{
		iso_31662: 'VE-O',
		estado: 'Nueva Esparta',
		capital: 'La Asunción',
		id_estado: 16,
	},
	{
		iso_31662: 'VE-P',
		estado: 'Portuguesa',
		capital: 'Guanare',
		id_estado: 17,
	},
	{
		iso_31662: 'VE-R',
		estado: 'Sucre',
		capital: 'Cumaná',
		id_estado: 18,
	},
	{
		iso_31662: 'VE-S',
		estado: 'Táchira',
		capital: 'San Cristóbal',
		id_estado: 19,
	},
	{
		iso_31662: 'VE-T',
		estado: 'Trujillo',
		capital: 'Trujillo',
		id_estado: 20,
	},
	{
		iso_31662: 'VE-W',
		estado: 'Vargas',
		capital: 'La Guaira',
		id_estado: 21,
	},
	{
		iso_31662: 'VE-U',
		estado: 'Yaracuy',
		capital: 'San Felipe',
		id_estado: 22,
	},
	{
		iso_31662: 'VE-V',
		estado: 'Zulia',
		capital: 'Maracaibo',
		id_estado: 23,
	},
	{
		iso_31662: 'VE-A',
		estado: 'Distrito Capital',
		capital: 'Caracas',
		id_estado: 24,
	},
];
